name: Visit GitHub Page

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions UI
  schedule:
    - cron: '0 * * * *' # Runs every hour; adjust as needed

jobs:
  visit-page:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*' # Installs the latest LTS version of Node.js

      - name: Install dependencies
        run: npm install selenium-webdriver

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Visit Script
        run: |
          node scripts/visit.js
